name: Student app CI/CD pipeline

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
  workflow_dispatch:
    
  
jobs:

  # -------------------------------------------
  # Job 1 : Install python and Run the tests
  # -------------------------------------------
  
  test:
    name: run Tests
    runs-on: ubuntu-latest

    steps:

      # Download code from the github into runner  
      - name: checkout the code
        uses: actions/checkout@v4

      # Install python 3.11 on the runner machine
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install Dependencies from the requirements.txt
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      # Runs the tests
      - name: Run tests
        run: |
          pytest test_app.py -v

  # ---------------------------------------------------
  # Job 2 : Deploy
  #----------------------------------------------------

  deploy:

  

